[package]
name = "windows_app_bar"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Windows AppBar API"

[dependencies]
log.workspace = true
raw-window-handle.workspace = true
thiserror.workspace = true
windows.workspace = true
